'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("prima riga intestazione")>  _
        Public Property intestazione1() As String
            Get
                Return CType(Me("intestazione1"),String)
            End Get
            Set
                Me("intestazione1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("seconda riga intestazione")>  _
        Public Property intestazione2() As String
            Get
                Return CType(Me("intestazione2"),String)
            End Get
            Set
                Me("intestazione2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("terza riga intestazione")>  _
        Public Property intestazione3() As String
            Get
                Return CType(Me("intestazione3"),String)
            End Get
            Set
                Me("intestazione3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Indagini relative a....")>  _
        Public Property oggetto() As String
            Get
                Return CType(Me("oggetto"),String)
            End Get
            Set
                Me("oggetto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Contiene fotografie di....")>  _
        Public Property contenutoDettaglio() As String
            Get
                Return CType(Me("contenutoDettaglio"),String)
            End Get
            Set
                Me("contenutoDettaglio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cognome e nome autore")>  _
        Public Property autore() As String
            Get
                Return CType(Me("autore"),String)
            End Get
            Set
                Me("autore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("comune")>  _
        Public Property luogo() As String
            Get
                Return CType(Me("luogo"),String)
            End Get
            Set
                Me("luogo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property gradoCognomeNome() As String
            Get
                Return CType(Me("gradoCognomeNome"),String)
            End Get
            Set
                Me("gradoCognomeNome") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property carattereDimensioneBase() As String
            Get
                Return CType(Me("carattereDimensioneBase"),String)
            End Get
            Set
                Me("carattereDimensioneBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IL COMANDANTE")>  _
        Public Property gruppoFirmaIRiga() As String
            Get
                Return CType(Me("gruppoFirmaIRiga"),String)
            End Get
            Set
                Me("gruppoFirmaIRiga") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property carattereDimensioneTitoloFoto() As String
            Get
                Return CType(Me("carattereDimensioneTitoloFoto"),String)
            End Get
            Set
                Me("carattereDimensioneTitoloFoto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Immagine nr.")>  _
        Public Property titoloFoto() As String
            Get
                Return CType(Me("titoloFoto"),String)
            End Get
            Set
                Me("titoloFoto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bIncorporaImmagini() As Boolean
            Get
                Return CType(Me("bIncorporaImmagini"),Boolean)
            End Get
            Set
                Me("bIncorporaImmagini") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property disposizioneColonne() As String
            Get
                Return CType(Me("disposizioneColonne"),String)
            End Get
            Set
                Me("disposizioneColonne") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property disposizioneRighe() As String
            Get
                Return CType(Me("disposizioneRighe"),String)
            End Get
            Set
                Me("disposizioneRighe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property carattereDimensioneDidascalia() As String
            Get
                Return CType(Me("carattereDimensioneDidascalia"),String)
            End Get
            Set
                Me("carattereDimensioneDidascalia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property fotoLarghezzaCM() As String
            Get
                Return CType(Me("fotoLarghezzaCM"),String)
            End Get
            Set
                Me("fotoLarghezzaCM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property fotoAltezzaCM() As String
            Get
                Return CType(Me("fotoAltezzaCM"),String)
            End Get
            Set
                Me("fotoAltezzaCM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Identificazione")>  _
        Public Property tipoFascicolo() As String
            Get
                Return CType(Me("tipoFascicolo"),String)
            End Get
            Set
                Me("tipoFascicolo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property newVersion() As Boolean
            Get
                Return CType(Me("newVersion"),Boolean)
            End Get
            Set
                Me("newVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bMemorizzaDidascalia() As Boolean
            Get
                Return CType(Me("bMemorizzaDidascalia"),Boolean)
            End Get
            Set
                Me("bMemorizzaDidascalia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("240")>  _
        Public Property fotoAltezzaTumb() As String
            Get
                Return CType(Me("fotoAltezzaTumb"),String)
            End Get
            Set
                Me("fotoAltezzaTumb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("320")>  _
        Public Property fotoLarghezzaTumb() As String
            Get
                Return CType(Me("fotoLarghezzaTumb"),String)
            End Get
            Set
                Me("fotoLarghezzaTumb") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SGraf.My.MySettings
            Get
                Return Global.SGraf.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
